# Generated by Django 4.1.5 on 2023-01-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0014_delete_productpicture'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_images', to='maincatalog.product', verbose_name='продукт'),
        ),
    ]
