# Generated by Django 4.1.5 on 2023-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[(None, 'Выберите тип страницы'), ('TXT', 'text'), ('FRM', 'form')], max_length=3, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='page',
            name='urlname',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='человекочитаемый url'),
        ),
    ]
