# Generated by Django 4.1.5 on 2023-01-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0003_alter_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maincatalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maincatalog.category'),
        ),
    ]
