# Generated by Django 4.1.5 on 2023-01-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0005_alter_category_parentcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maincatalog.category'),
        ),
    ]
