# Generated by Django 4.1.5 on 2023-01-23 19:28

from django.db import migrations, models
import django.db.models.deletion
import khanshop.enums


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0008_remove_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maincatalog.category', verbose_name='родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincatalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='подробное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=8, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=400, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(khanshop.enums.StatusChoice['YES'], 'в наличии'), (khanshop.enums.StatusChoice['LIM'], 'количество ограничено'), (khanshop.enums.StatusChoice['END'], 'нет в наличии'), (khanshop.enums.StatusChoice['ASK'], 'под заказ'), (khanshop.enums.StatusChoice['DEL'], 'снято с производства')], max_length=100, verbose_name='статус'),
        ),
    ]
