# Generated by Django 4.1.5 on 2023-01-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0009_alter_category_parentcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(blank=True, max_length=50, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincatalog.product', verbose_name='продукт')),
            ],
        ),
    ]
