# Generated by Django 4.1.5 on 2023-01-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0011_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='показывается'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='показывается'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основное'),
        ),
    ]
