# Generated by Django 4.1.5 on 2023-01-30 06:46

from django.db import migrations, models
import khanshop.enums


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0012_product_is_active_productpicture_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(khanshop.enums.StatusChoice['YES'], 'в наличии'), (khanshop.enums.StatusChoice['LIM'], 'количество ограничено'), (khanshop.enums.StatusChoice['END'], 'нет в наличии'), (khanshop.enums.StatusChoice['ASK'], 'под заказ'), (khanshop.enums.StatusChoice['DEL'], 'снято с производства')], max_length=3, verbose_name='статус'),
        ),
    ]
