# Generated by Django 4.1.5 on 2023-01-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0013_alter_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPicture',
        ),
    ]
