# Generated by Django 4.1.5 on 2023-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincatalog', '0014_delete_productpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urlname',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='человекочитаемый url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите статус товара'), ('YES', 'в наличии'), ('LIM', 'количество ограничено'), ('END', 'нет в наличии'), ('ASK', 'под заказ'), ('DEL', 'снято с производства')], max_length=3, verbose_name='статус'),
        ),
    ]
